#Minecraft server properties
#Fri Oct 09 13:16:24 UTC 2026
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=Prominence II - Hasturian Era 4.1.3
query.port=25565
pvp=true
generate-structures=true
max-chained-neighbor-updates=1000000
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
require-resource-pack=false
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
initial-disabled-packs=create_new_age\:create_new_age_monkey_edition,estrogen\:vanillamode,paladins_all_the_smites-1.20.1_1.0.zip,Lootr-BetterEnd-Compatibility-1.20-and-earlier-2.0.zip,onlyExcavators-balancing-1.20.1-1.0.0.zip,sunnier_skies_for_archon_1.20.1_1.0.0.zip,alms_recipe_additions-1.20.1_1.9.1.zip,SupernovaTempFix.zip,SkyVillages-GraveyardCompat-1.20.1-1.0.3.zip,LessStructures-SpacingTweaks-1.20.1-2.1.56.zip,ichphilipp-s-endcity-better-end-1-18-1.zip,alms_oil_compat_1.20.1-1.0.0.zip,rpg_series_loot_table_tweaks_1.20.1_1.1.0.zip,WDA-VanillaLoot-1.18.2-1.19.2-0.0.1.zip,regions_unexplored_farmers_delight_compat_1.20.1_1.0.0.zip,simplyswords_all_the_death_strike-1.20.1_1.1.0.zip,Lootr-BetterNether-Compatibility-1.20-and-earlier.zip,bundles_no_more_loot_table_tweaks_1.20.1_1.0.0.zip,BE_default_endgen_fix_1.20.x.zip,Daggers_Fix.zip,quiver_recipe_supplementaries-1.20.1_1.0.zip,simplyswords_all_the_smites-1.20.1_1.1.0.zip,artifacts_loot_table_tweaks_1.20.1_1.1.0.zip,spell_enchants_for_all_1.1.zip,simplyswords_join_book.zip,simplyswords_all_the_festering_strike-1.20.1_1.1.0.zip,tierify-prominence-tweaks-2.0.2.zip,ElocinDev-Travelers-Comfort-Datapack.zip,soulslikeweaponry_all_the_smites-1.20.1_1.0.0.zip,spellblades_unlimited_1.20.1-1.0.0.zip,bard_spell_tweaks_1.20.1_1.0.0.zip,Scarecrow_Obliterator.zip,SkyVillages-WaystonesCompat-1.20.1-1.0.3-fabric.zip,ShutUpMobsOfMythology.zip,Iron.Chests.Restocked.Fix.zip,enchanted_mutandis_tweaks.zip,archers_expansion_spell_tweaks_1.20.1_1.2.0.zip,spell_enchants_for_all_armor_edition_1.20.1-1.4.0.zip,Supplementaries Compat 1.2.zip,MSW Guns' Upswing (2).zip,spellbladenext_spell_tweaks_1.20.1_1.0.0.zip,SkyVillages-SupplementariesCompat-1.20.1-1.0.3.1.zip,create_applied_energistics_recipes_alts_1.20.1-1.0.1.zip,lightning_unlimited-1.20.1-1.1.0 (1).zip,TrophyAdjustments.zip,SkyVillages-FarmersDelightCompat-1.20.1-1.0.3.zip,artifacts_loot_table_tweaks_1.20.1_1.0.1.zip,TierAdjustments.zip,crossbows_reloaded_1.20.1_1.0.0.zip,DKTempFix.zip,death_knights_spell_tweaks_1.20.1-1.0.zip,mcdw_all_the_smites-1.20.1_1.0.zip,HighLevelSpellbooks.zip,auto_fire_hooks.zip,endrem_apoth_compat.zip,WDA-NoFlyingStructures-1.18.2-1.19.2.zip
broadcast-rcon-to-ops=true
view-distance=8
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=25565
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=6
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla,fabric,lithostitched\:breaks_seed_parity
level-type=bclib\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
